# Generated by Django 5.0.3 on 2024-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.IntegerField(verbose_name='章节名称')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='课程名')),
                ('chapter_num', models.IntegerField(verbose_name='章节数')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('stu_num', models.IntegerField(verbose_name='学生人数')),
                ('course_url', models.URLField(verbose_name='课程网址')),
                ('teach_time', models.CharField(max_length=2, verbose_name='上课时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('uptime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('chapter', models.CharField(max_length=30, verbose_name='第几章')),
                ('upload_file', models.FileField(upload_to='file', verbose_name='课程资源')),
            ],
            options={
                'verbose_name': '课件',
                'verbose_name_plural': '课件',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='视频名称')),
                ('video_url', models.URLField(default='https:www.baidu.com', max_length=50, verbose_name='视频网址')),
                ('upload_file', models.FileField(upload_to='video/', verbose_name='上传视频')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
