# Generated by Django 5.0.3 on 2024-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="goal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="recitation",
            field=models.IntegerField(default=0),
        ),
    ]
