# Generated by Django 5.0.3 on 2024-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('captcha', models.TextField(max_length=5)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
