# Generated by Django 5.0.3 on 2024-05-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('password', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField(default=30)),
                ('password', models.CharField(max_length=20)),
                ('course', models.ManyToManyField(related_name='teachers', to='study.course')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender')),
            ],
        ),
    ]
