# Generated by Django 5.0.3 on 2024-06-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=2, verbose_name='题型')),
                ('content', models.CharField(max_length=100, verbose_name='题目')),
                ('weight', models.IntegerField(verbose_name='分值')),
                ('answer', models.CharField(max_length=100, verbose_name='答案')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=1, verbose_name='题型')),
                ('content', models.CharField(max_length=100, verbose_name='题目')),
                ('A_CHOICES', models.CharField(max_length=255, verbose_name='A选项')),
                ('B_CHOICES', models.CharField(max_length=255, verbose_name='B选项')),
                ('C_CHOICES', models.CharField(max_length=255, verbose_name='C选项')),
                ('D_CHOICES', models.CharField(max_length=255, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, verbose_name='答案')),
                ('weight', models.IntegerField(verbose_name='分值')),
                ('chapter', models.CharField(max_length=30, verbose_name='章节')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=-1, verbose_name='测验成绩')),
            ],
        ),
        migrations.CreateModel(
            name='SubAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, null=True, verbose_name='作答')),
                ('score', models.IntegerField(default=-1, verbose_name='得分')),
            ],
            options={
                'verbose_name': '主观题作答',
                'verbose_name_plural': '主观题作答',
            },
        ),
        migrations.CreateModel(
            name='Subjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=3, verbose_name='题型')),
                ('content', models.CharField(max_length=100, verbose_name='题目')),
                ('weight', models.IntegerField(verbose_name='分值')),
            ],
            options={
                'verbose_name': '主观题',
                'verbose_name_plural': '主观题',
            },
        ),
        migrations.CreateModel(
            name='BFAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, verbose_name='作答')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('blankfilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BFAnswers', to='exam.blankfilling')),
            ],
            options={
                'verbose_name': '填空题作答',
                'verbose_name_plural': '填空题作答',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, verbose_name='作答')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChoiceAnswers', to='exam.choice')),
            ],
            options={
                'verbose_name': '选择题作答',
                'verbose_name_plural': '选择题作答',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='考试名称')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('chapter', models.IntegerField(default=0, verbose_name='章节数')),
                ('question_num', models.IntegerField(verbose_name='题目数')),
                ('time_long', models.IntegerField(default=0, verbose_name='考试时长')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
            },
        ),
    ]
