# Generated by Django 5.0.3 on 2024-12-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=10)),
                ("dynasty", models.CharField(max_length=10)),
                ("text", models.TextField()),
                ("book_id", models.IntegerField()),
            ],
            options={
                "db_table": "Article",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="唐诗宋词四十首", max_length=200)),
                ("goal", models.IntegerField(default=30)),
                (
                    "avatar",
                    models.CharField(
                        default="https://img.js.design/assets/img/6738a078de61f2f62e79fcc5.png#ce2d243f7bd7832fae04e0eeca122220",
                        max_length=666,
                    ),
                ),
            ],
            options={
                "db_table": "book",
            },
        ),
        migrations.CreateModel(
            name="EasySentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("article_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "easysentence",
            },
        ),
        migrations.CreateModel(
            name="HardSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("count", models.IntegerField(default=0)),
                ("article_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "hardsentence",
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("article_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "process",
            },
        ),
        migrations.CreateModel(
            name="ArticleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("difficulty", models.IntegerField(default=0)),
                ("user_id", models.IntegerField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.article"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
            ],
            options={
                "db_table": "ArticleUser",
            },
        ),
        migrations.CreateModel(
            name="BookUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("status", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
            ],
            options={
                "db_table": "BookUser",
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.hardsentence",
                    ),
                ),
            ],
            options={
                "db_table": "segment",
            },
        ),
    ]
