# Generated by Django 5.0.3 on 2024-12-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleuser",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="bookuser",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="easysentence",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="hardsentence",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="process",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
    ]
