# Generated by Django 5.0.3 on 2024-12-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_articleuser_user_id_alter_bookuser_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.IntegerField(default=100),
        ),
    ]
