# Generated by Django 5.0.3 on 2024-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="avatar",
            field=models.CharField(max_length=666, null=True),
        ),
    ]
