# Generated by Django 5.0.3 on 2024-12-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="goal",
        ),
    ]
