# Generated by Django 5.0.3 on 2024-05-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-pub_date', 'price')},
        ),
    ]
