# Generated by Django 5.0.3 on 2024-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=-1, verbose_name='课程成绩')),
            ],
            options={
                'verbose_name': '学生课程表',
                'verbose_name_plural': '学生课程表',
            },
        ),
    ]
